baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "<Matafy Yourstrulee>'s blog"
  subtitle    = "Port of Casper 2.x for Hugo"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "<Matafy Yourstrulee>'s blog"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "Hesmatafy"
  fbName = ""
  githubName = "Yourstrulee"
  linkedinName = ""
  mediumName = ""

  logo = ""
  orgName = "EM"
  orgWebsite = ""
  orgDescription = ""

  showSupport = true

  author = "EM"
  authorAvatar = ""
  authorLocation = "Lagos ,NG"
  authorWebsite = ""
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tutorial"
  url = "/categories/turorial/"
  weight = 5


